version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/cvs-go-server
    overwrite: yes

permissions:
  - object: /home/ubuntu/cvs-go-server
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu