spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DEV_DB}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PWD}

  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret-key: ${SECRET_KEY}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: cvs-go
    region:
      static: ap-northeast-2
    stack:
      auto: false
