spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${PROD_DB}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PWD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB102Dialect
        default_batch_fetch_size: 1000
jwt:
  secret-key: ${SECRET_KEY}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: cvs-go
    region:
      static: ap-northeast-2
    stack:
      auto: false
