spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cvsgo
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: ${SECRET_KEY}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: cvs-go
    region:
      static: ap-northeast-2
    stack:
      auto: false
