name: PR Tests on Develop

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Controller and Service Tests with Gradle
        run: |
          ./gradlew test --tests "com.cvsgo.controller.*"
          ./gradlew test --tests "com.cvsgo.service.*"
          
      - name: Report test result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
           files: 'build/test-results/**/*.xml'
